-- ==========================================================
-- LADAKH-SHIELD: HIGH-ALTITUDE ELECTRONIC SYSTEM MONITORING
-- Database Schema: MySQL 8.0+
-- Hardware: ESP32 + BME280 + INA219/INA226 + LoRa SX1278
-- ==========================================================

CREATE DATABASE IF NOT EXISTS `ladakh_shield_db` 
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `ladakh_shield_db`;

-- 1. SENSOR TELEMETRY TABLE
-- Records raw and calculated values from BME280 and INA219/INA226 sensors
CREATE TABLE IF NOT EXISTS `sensor_data` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `device_id` VARCHAR(32) NOT NULL DEFAULT 'LSH-24-05-0017',
    `location` VARCHAR(64) NOT NULL DEFAULT 'Ladakh Sector Alpha (4850m)',
    `temperature` DECIMAL(5, 2) NOT NULL COMMENT 'Ambient / enclosure temp in °C (BME280)',
    `pressure` DECIMAL(6, 2) NOT NULL COMMENT 'Barometric pressure in kPa (BME280)',
    `humidity` DECIMAL(5, 2) NOT NULL COMMENT 'Relative humidity in % (BME280)',
    `voltage` DECIMAL(5, 2) NOT NULL COMMENT 'Bus voltage in Volts (INA219/226)',
    `current` DECIMAL(5, 2) NOT NULL COMMENT 'Load current in Amperes (INA219/226)',
    `power` DECIMAL(6, 2) GENERATED ALWAYS AS (`voltage` * `current`) STORED COMMENT 'Calculated Power in Watts',
    `battery_health` TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT 'Estimated battery health percentage',
    `data_source` ENUM('LIVE_HARDWARE', 'SIMULATED', 'SD_SYNC') NOT NULL DEFAULT 'SIMULATED',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_device_time` (`device_id`, `created_at`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB;

-- 2. EQUIPMENT STATUS TABLE
-- Tracks status for the 5 monitored subsystems via Universal Module
CREATE TABLE IF NOT EXISTS `equipment_status` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `equipment_id` ENUM('drone', 'radar', 'radio', 'computer', 'battery') NOT NULL,
    `equipment_name` VARCHAR(64) NOT NULL,
    `status` ENUM('NORMAL', 'WARNING', 'CRITICAL', 'OFFLINE') NOT NULL DEFAULT 'NORMAL',
    `operating_status` VARCHAR(128) NOT NULL,
    `temperature` DECIMAL(5, 2) NOT NULL,
    `voltage` DECIMAL(5, 2) NOT NULL,
    `current` DECIMAL(5, 2) NOT NULL,
    `health_percentage` TINYINT UNSIGNED NOT NULL,
    `parameters_json` JSON COMMENT 'Subsystem-specific sensor metrics in JSON format',
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_equipment_status` (`equipment_id`, `status`)
) ENGINE=InnoDB;

-- 3. ALERTS TABLE
-- Historical and real-time alert events generated by the Rule-Based Risk Engine
CREATE TABLE IF NOT EXISTS `alerts` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `alert_uuid` VARCHAR(64) NOT NULL UNIQUE,
    `severity` ENUM('CRITICAL', 'WARNING', 'INFO') NOT NULL,
    `title` VARCHAR(128) NOT NULL,
    `message` TEXT NOT NULL,
    `equipment_id` ENUM('drone', 'radar', 'radio', 'computer', 'battery', 'SYSTEM') DEFAULT 'SYSTEM',
    `acknowledged` BOOLEAN NOT NULL DEFAULT FALSE,
    `acknowledged_by` VARCHAR(64) NULL,
    `acknowledged_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_severity` (`severity`),
    INDEX `idx_acknowledged` (`acknowledged`)
) ENGINE=InnoDB;

-- 4. ADAPTIVE PROTECTION ACTION LOGS
-- Records automatic and manual interventions by Heater, Cooling Fan, and MOSFET Isolator
CREATE TABLE IF NOT EXISTS `protection_logs` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `subsystem` ENUM('HEATER', 'COOLING_FAN', 'MOSFET_POWER', 'EMERGENCY_MODE') NOT NULL,
    `action` ENUM('AUTO_ON', 'AUTO_OFF', 'MANUAL_ON', 'MANUAL_OFF', 'TRIP_ISOLATION', 'RESET') NOT NULL,
    `reason` VARCHAR(255) NOT NULL,
    `trigger_temperature` DECIMAL(5, 2) NULL,
    `trigger_current` DECIMAL(5, 2) NULL,
    `executed_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 5. LORA COMMUNICATION LOGS
-- Tracks SX1278 packet transmissions, RSSI, SNR, and link quality
CREATE TABLE IF NOT EXISTS `communication_logs` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `node_address` VARCHAR(16) NOT NULL,
    `gateway_address` VARCHAR(16) NOT NULL,
    `frequency_mhz` DECIMAL(6, 3) NOT NULL DEFAULT 868.100,
    `rssi_dbm` SMALLINT NOT NULL,
    `snr_db` DECIMAL(4, 1) NOT NULL,
    `packet_num` INT UNSIGNED NOT NULL,
    `payload_hex` VARCHAR(255) NOT NULL,
    `payload_size_bytes` SMALLINT UNSIGNED NOT NULL,
    `logged_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Seed initial equipment definitions
INSERT INTO `equipment_status` (`equipment_id`, `equipment_name`, `status`, `operating_status`, `temperature`, `voltage`, `current`, `health_percentage`)
VALUES 
('drone', 'Tactical Drone (UAV)', 'NORMAL', 'Hover Patrol / Standby Beacon', -18.2, 12.35, 2.60, 84),
('radar', 'Border Surveillance Radar', 'NORMAL', 'Sector Scan 180° Active', -15.6, 12.42, 3.10, 91),
('radio', 'VHF/UHF Tactical Radio', 'NORMAL', 'Standby RX / Mesh Relay', -19.4, 12.38, 1.40, 88),
('computer', 'Tactical Edge Computer', 'NORMAL', 'Telemetry Aggregation & Inference', 28.3, 12.39, 2.10, 95),
('battery', 'Cold-Resistant Power Pack', 'NORMAL', 'Discharging Nominally', -14.8, 12.41, 2.55, 82)
ON DUPLICATE KEY UPDATE `updated_at` = CURRENT_TIMESTAMP;
